baseurl = "/"
title = "YB Gwon's ..."
copyright = "Copyright &copy; 2019 - Author Name"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true
disqusShortname = "ybgwon"

[author]
    name = "ybgwon"
    github = "ybgwon"
    # gitlab = ""
    # linkedin = ""
    # facebook = ""
    # twitter = ""
    # instagram = ""

[params]
    tagline = "Personal Blog for creative and technical writing"
    description = "YB Gwon's blog for creative and technical writing."
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = []  #Optional Customised CSS
    #favicon = ""
